### PR TITLE
feat: split catchments, modules and formConfig syncs

### LINKED ISSUE #29: Call to module-list has confusing "last_modified" date in 2.0.6-dev
### Bug Description

When logging in as a new user all queries should have `last_modified` as 0. In the bahis-desk logs it announces the call with `0`, however in server logs I see
Screenshot 2022-12-26 at 12 09 28

### To Reproduce

4. See error.

### Expected Behaviour

Screenshot 2022-12-26 at 12 09 12

### Additional Context

As long as you actually delete database in 2.0.6-dev on every new user log in I don't understand how it can ba happening.

### PR DESCRIPTION
**Pull request by ChasNelson1990**
## Description

**Work in progress**

Building upon discussions with @mixmixmix, we want to try and split up the catchments and modules API calls and we think this is possible.

This PR _should_ be the front changes for this:

* update electron to v13+ so dev tools work on Linux
* we sync formConfig (which I think sets up the db) on new dbs
* add the new catchments endpoint and use that to sync catchments on new dbs
* split out the module-list endpoint and sync that on all syncs

closes #29 
relates road86/bahis-serve#9 <- back end changes

## Checklist

- [ ] I have read the road86 Contribution Guide.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
@mixmixmix - I think the last commit should have the following:

- a few extra logs
- an electron app that successfully hits bahis-serve API endpoints, and gets results for everything
- an electron app that successfully fills the sqlite db out as expected
- an electron app that reliable gets passed the login form but...

still todo:

- [ ] I can now recreate #28 reliably we need to fix this lol

However, I think this is due to react not rerendering , which means we aren't updating the props/state where we need to.

I think it's basically this function: https://github.com/road86/bahis-desk/blob/d29af2ecd13ffa52a75c5bef59918ccd0131c83a/src/containers/Menu/index.tsx#L82

It should be fetching and updating the menu options but it's only called on the component mount and so we need an additional prop or state that causes a recall and rerender when something changes electron-side.

One to discuss tomorrow but feel free to have a play with where we are and check you agree with me?!

**Comment by ChasNelson1990** [comment]
Okay, so @mixmixmix, this latest commit is a step forward. We now have the following situation:

1. on a clean dB, the electron app makes all the right calls, gets all the right data and puts that in the new local dB - this is not quick but I have no timed it yet; unfortunately, this renders a blank screen as it tries to render menus before it has them!
2. but... if you hit "Sync", it syncs fine and the menus correctly render
3. or... if you log out and log back in again (not deleting the local db) the menus render correctly

It is late here so I have not fully tested this; however, if you have a play and agree that this is the current situation then all we need to do is:

- [ ]  give the user more information about what is going on so that they don't think things have frozen and shut the stuff down or rage click or submit an issue
- [ ] sort out the electron <> front end messaging so that it doesn't try to render Menu until _after_ the app definition is correctly set
- [ ] fully test things

**Comment by mixmixmix** [comment]
It all sounds great. If the sync button is available it is really good enough, as we have been instructiong them to do a first sync after login anyway.
Almost all of the app users, will already be logged in their apps, so the main thing to verify is how the system works with change of version with a DB already set up.

**Comment by ChasNelson1990** [comment]
@mixmixmix this is ready for another round of your tests

**Review by mixmixmix — APPROVED** [review]
Third time lucky.

**Pull request merged**
